<?php
/**
 * Class FieldtypeAssistedURL
 *
 * @author Marco Stoll <m.stoll@core4.de>
 * @link http://core4.de CORE4 GmbH & Co. KG
 * @copyright Copyright (c) 2015, CORE4 GmbH & Co. KG
 * @license MIT http://opensource.org/licenses/MIT
 * @version 1.0.0
 * @see http://www.processwire.com
 * @filesource
 */

/**
 * Class FieldtypeAssistedURL
 */
class FieldtypeAssistedURL extends FieldtypeURL
{
    /**
     * Get information about this module
     *
     * @return array
     */
    public static function getModuleInfo()
    {
        return [
            'title' => 'AssistedURL Field',
            'version' => 100,
            'summary' => 'Field that stores an URL providing controls for selecting internal pages and files.',
            'installs' => 'InputfieldAssistedURL',
        ];
    }

    /**
     * Per Module interface, this template method is called when all system classes are loaded and ready for API usage
     */
    public function init()
    {
        parent::init();
    }

    /**
     * Return new instance of the Inputfield associated with this Fieldtype
     *
     * @param Page $page
     * @param Field $field
     * @return Inputfield
     */
    public function getInputfield(Page $page, Field $field)
    {
        /** @var InputfieldAssistedURL $inputField */
        $inputField = $this->modules->get("InputfieldAssistedURL");
        $inputField->setPage($page);

        return $inputField;
    }

    /**
     * get values converted when fetched from db
     *
     */
    public function ___wakeupValue(Page $page, Field $field, $value) {
        $urlParts = explode("?", $value);
        if(is_numeric($urlParts[0])) {
            $return = $this->wire('pages')->get($urlParts[0])->path . (isset($urlParts[1]) ? '?' . $urlParts[1] : '');
        }
        else {
            $return = $value;
        }
        return $return;
    }

    /**
     * return converted from object to array for storing in database
     *
     */
    public function ___sleepValue(Page $page, Field $field, $value) {
        if(strpos($value, '//') === false) {
            $urlParts = explode("?", $value);
            $p = $this->wire('pages')->get($urlParts[0]);
            if($p->id) {
                $return = $p->id . (isset($urlParts[1]) ? '?' . $urlParts[1] : '');
            }
            else {
                $return = $value;
            }
        }
        else {
            $return = $value;
        }
        return $return;
    }

}
