<?php
/**
 * Class InputfieldAssistedURL
 *
 * @author Marco Stoll <m.stoll@core4.de>
 * @link http://core4.de CORE4 GmbH & Co. KG
 * @copyright Copyright (c) 2015, CORE4 GmbH & Co. KG
 * @license MIT http://opensource.org/licenses/MIT
 * @version 1.0.0
 * @see http://www.processwire.com
 * @filesource
 */

/**
 * Class InputfieldAssistedURL
 */
class InputfieldAssistedURL extends Inputfield {

    /**
     * @var Page
     */
    protected $page;

    /**
     * Get information about this module
     *
     * @return array
     */
    public static function getModuleInfo() {
        return [
            'title' => 'AssistedURL Input',
            'version' => '2.0.1',
            'summary' => 'Input field for assisted urls.',
            'requires' => 'FieldtypeAssistedURL',
            'author' => 'Marco Stoll, Adrian Jones'
        ];
    }

    /**
     * Sets the current page
     *
     * @param Page $page
     */
    public function setPage(Page $page) {
        $this->page = $page;
    }

    /**
     * Render the entire input area for Events
     */
    public function ___render() {

        $field = new InputfieldURL();
        $field->set('name', $this->attr('name'));
        $field->set('value', $this->attr('value'));
        $field->set('class', 'InputfieldAssistedURLInput');

        $btn = $this->modules->get('InputfieldButton');
        $btn->attr('id', $this->attr('name') . "_assistedurl_open");
        $page = $this->page;
        $n = 0;
        while(wireInstanceOf($page, 'RepeaterPage') && ++$n < 10) {
            $page = $page->getForPage();
        }
        $btn->attr('data-page-id', $page->id);
        $btn->class .= " InputfieldAssistedURLOpen";
        $btn->icon = 'link';
        $btn->value = '';

        return $btn->render() . '<div class="InputfieldAssistedUrlText">' . $field->render() . '</div>';
    }
}
